# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_brms_data": "core.ipynb",
         "get_stan_code": "core.ipynb",
         "fit": "core.ipynb"}

modules = ["pybrms.py"]

doc_url = "https://adamhaber.github.io/pybrms/"

git_url = "https://github.com/adamhaber/pybrms/tree/master/"

def custom_doc_links(name): return None